# Twilio API Configuration
twilio:
  account_sid: "AC42104f3d5d6cad211714b95ac65ce90b"
  auth_token: "aa26b7a1a041e6b5a3caf38bc4437f57"
  phone_number: "+14155238886"
  admin_phone_number: "+6282199118088"

# Database Configuration
database:
  path: "database/jaysecurity.db"

# Logging Configuration
logging:
  file_path: "logs/jaysecurity.log"

# Attack Detection Configuration
detection:
  threshold_level: "medium"
